<a href="https://colab.research.google.com/github/Tejaswinirobbi-huee/Iris-dataset/blob/main/fds4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import pandas as pd

In [17]:
df = pd.read_csv("iris.csv")

In [18]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [20]:
df.mean(numeric_only=True)

Id               75.500000
SepalLengthCm     5.843333
SepalWidthCm      3.054000
PetalLengthCm     3.758667
PetalWidthCm      1.198667
dtype: float64

In [21]:
df.median(numeric_only=True)

Id               75.50
SepalLengthCm     5.80
SepalWidthCm      3.00
PetalLengthCm     4.35
PetalWidthCm      1.30
dtype: float64

In [22]:
df.mode()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.0,3.0,1.5,0.2,Iris-setosa
1,2,NaN,NaN,NaN,NaN,Iris-versicolor
2,3,NaN,NaN,NaN,NaN,Iris-virginica
3,4,NaN,NaN,NaN,NaN,NaN
4,5,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
145,146,NaN,NaN,NaN,NaN,NaN
146,147,NaN,NaN,NaN,NaN,NaN
147,148,NaN,NaN,NaN,NaN,NaN
148,149,NaN,NaN,NaN,NaN,NaN
149,150,NaN,NaN,NaN,NaN,NaN

In [23]:
numeric_data = df.select_dtypes(include='number')

In [24]:
central_tendency = pd.DataFrame({
    "Mean": numeric_data.mean(),
    "Median": numeric_data.median(),
    "Mode": numeric_data.mode().iloc[0]
})

In [25]:
print(central_tendency)

                    Mean  Median  Mode
Id             75.500000   75.50   1.0
SepalLengthCm   5.843333    5.80   5.0
SepalWidthCm    3.054000    3.00   3.0
PetalLengthCm   3.758667    4.35   1.5
PetalWidthCm    1.198667    1.30   0.2